### ISSUE TITLE
terminate 

### ISSUE THREAD

**Issue by q6654282** [tj8519/astrominer#8] opened 2022-10-15 10:49 UTC
terminate called after throwing an instance of 'std::length_error'    what():  basic_string::_M_replace_aux

ARM This problem occurs after running for a period of time

**Comment by q6654282** [comment] 2022-10-15 10:54
for rpc

**Comment by q6654282** [comment] 2022-10-16 09:21
Have people seen my news？？

**Comment by tj8519** [comment] 2022-10-16 09:40
@q6654282 should be fixed in the latest version

**Comment by q6654282** [comment] 2022-10-16 11:09
The same problem! Automatically terminate after running for a period of time

**Comment by q6654282** [comment] 2022-10-16 11:21
![1665919229350](https://user-images.githubusercontent.com/4101732/196032426-38f39cd7-e5cd-4228-b7a6-4f3c15c8bad2.png)

**Comment by q6654282** [comment] 2022-10-16 14:58
![1665932280224](https://user-images.githubusercontent.com/4101732/196042536-067c0f66-21fe-4088-abde-9d83d98896fb.png)
This problem has occurred! I don't know if I can help

**Comment by tj8519** [comment] 2022-10-16 15:07
hello @q6654282 ,
please provide your hardware and spec, we will investigate further

**Comment by q6654282** [comment] 2022-10-16 15:40
Samsung G973U (Snapdragon 855 Octa-Core processor and 8GB of RAM,128GB )
Termux-ubuntu

**Comment by q6654282** [comment] 2022-10-17 11:48
@tj8519 The same problem!

**Comment by q6654282** [comment] 2022-10-18 05:27
Already running - k 2

**Comment by tj8519** [comment] 2022-10-18 07:00
thanks for keep monitoring the issue. Sadly, I still can't reproduce your error on my machine, so I can't give you the exact advice. I'll inform you when the bug is found.

**Comment by q6654282** [comment] 2022-10-18 07:48
good Thank you for your concern

**Comment by tj8519** [comment] 2022-10-30 14:20
@q6654282 Please try version V1.5 if it's okay
https://github.com/tj8519/astrominer/releases/tag/V1.5

**Closed** 2022-11-03 05:11 UTC
